export const INIT_LOAD = "INIT_LOAD";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAIL = "SEARCH_FAIL";
export const PAGE_LOAD = "PAGE_LOAD";
export const CREATE_NEW_USER = "CREATE_NEW_USER";


export const INIT_LOAD_ASYN = "INIT_LOAD_ASYN";
export const SEARCH_SUCCESS_ASYN = "SEARCH_SUCCESS_ASYN";
export const SEARCH_FAIL_ASYN = "SEARCH_FAIL_ASYN";
export const PAGE_LOAD_ASYN = "PAGE_LOAD_ASYN";
export const CREATE_NEW_USER_ASYN = "CREATE_USER_ASYN";

export const SORT_BY = "SORT_BY"
export const NEW_USER = 'CREATE_NEW_USER'
export const RELOAD = "RELOAD";
export const NEW_FILTERS_RULE = "RELOAD_FILTER_RULE";
export const CLEAR_FILTER_RULE = "CLEAR_FILTER_RULE"
export const NEW_FILTER_STATE = "NEW_FILTER_STATE";
export const CLEAR_FILTER_STATE = "CLEAR_FILTER_STATE";

export const NEW_FILTER_DATE = "NEW_FILTER_DATE";
export const CLEAR_FILTER_DATE = "CLEAR_FILTER_DATE";
export const NEW_ASSET = 'CREATE_NEW_ASSET'


export const LOAD_NEW_ASSIGNMENT = "LOAD_NEW_ASSIGNMENT";
export const LOAD_NEW_ASSET = "LOAD_NEW_ASSET";
export const LOAD_NEW_ASSET_HISTORY = "LOAD_NEW_ASSET_HISTORY";


export const LOAD_NEW_ASSET_SORT = "LOAD_NEW_ASSET_SORT";
export const LOAD_NEW_ASSIGNMENT_SORT = "LOAD_NEW_ASSIGNMENT_SORT";


export const LOAD_NEW_ASSET_STATE_FILTER = "LOAD_NEW_ASSET_STATE_FILTER";
export const LOAD_NEW_ASSET_CATEGORY_FILTER = "LOAD_NEW_ASSET_CATEGORY_FILTER";


export const LOAD_NEW_ASSET_PAGE = "LOAD_NEW_ASSET_PAGE";

