export const LOAD_NEW_SORT_RULE = "LOAD_NEW_SORT_RULE";
export const LOAD_CURRENT_PAGE = "LOAD_CURRENT_PAGE";
export const LOAD_NEW_FILTER_RULE = "LOAD_NEW_FILTER_RULE";
export const LOAD_NEW_KEYWORD = "LOAD_NEW_KEYWORD";
export const LOAD_DISABLE_CODE = "LOAD_DISABLE_CODE";
export const LOAD_NEW_USER = "LOAD_NEW_USER";


export const LOAD_NEW_ASSET = "LOAD_NEW_ASSET";
export const LOAD_NEW_ASSET_SORT_RULE = "LOAD_NEW_ASSET_SORT_RULE";
export const LOAD_NEW_ASSET_KEYWORD = "LOAD_NEW_ASSET_KEYWORD";
export const LOAD_NEW_ASSET_CATEGORY_FILTER = "LOAD_NEW_ASSET_CATEGORY_FILTER";
export const LOAD_NEW_ASSET_STATE_FILTER = "LOAD_NEW_ASSET_STATE_FILTER";
export const LOAD_NEW_ASSET_PAGE_NUMBER = "LOAD_NEW_ASSET_PAGE_NUMBER";
export const LOAD_NEW_ASSET_DISPLAY_LIST = "LOAD_NEW_ASSET_DISPLAY_LIST";
export const LOAD_ASSET_TOTAL_PAGE = "LOAD_ASSET_TOTAL_PAGE"



export const LOAD_NEW_ASSIGNMENT_PAGE_NUMBER = "LOAD_NEW_ASSIGNMENT_PAGE_NUMBER";
export const LOAD_NEW_ASSIGNMENT_KEYWORD = "LOAD_NEW_ASSIGNMENT_KEYWORD";
export const LOAD_NEW_ASSIGNMENT_DATE_FILTER = "LOAD_NEW_ASSIGNMENT_DATE_FILTER";
export const LOAD_NEW_ASSIGNMENT_STATE_FILTER = "LOAD_NEW_ASSIGNMENT_STATE_FILTER";
export const LOAD_NEW_ASSIGNMENT_SORT_RULE = "LOAD_NEW_ASSIGNMENT_SORT_RULE";